name: Join the Team
description: Apply to join A Game of Cubes (Lore, Builder, Developer, Content Creator, Tester)
title: "Application: [Role] - YourName"
labels: ["application", "needs-review"]
assignees: ["diskawrs"]

body:
  - type: markdown
    attributes:
      value: |
        # ✨ Join the A Game of Cubes Team
        Please complete the application below.

  - type: dropdown
    id: role
    attributes:
      label: Which role are you applying for?
      options:
        - Lore & Story
        - Landscape & Structures
        - Developer
        - Content Creator (Streams / Videos)
        - Tester
    validations:
      required: true

  - type: textarea
    id: experience
    attributes:
      label: Briefly describe your experience
      placeholder: "Background, examples, past projects, skills, etc."
    validations:
      required: true

  - type: textarea
    id: devskills
    attributes:
      label: Developer Skills (MMOCore, Denizen, MythicMobs)
      placeholder: "Optional unless applying as Developer."
    validations:
      required: false

  - type: textarea
    id: links
    attributes:
      label: Links (portfolio, GitHub, screenshots, videos)
      placeholder: "Please include at least one relevant link."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why do you want to join A Game of Cubes?
      placeholder: "Short answer is fine."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ✔ Applications are handled on GitHub only  
        ✔ Links are required so we can verify your work  
        ✔ We review applications as time allows  
