name: Join the Team
description: Apply to join A Game of Cubes as a Content Creator, Builder, Developer, or Tester.
title: "Application: [Role] - YourName"
labels: ["application"]
assignees: ["diskawrs"]

body:
  - type: markdown
    attributes:
      value: |
        # ✨ Join the A Game of Cubes Team
        
        Thanks for your interest in contributing!  
        Please fill out the details below — short and clear answers are fine.

  - type: dropdown
    id: role
    attributes:
      label: Which role are you applying for?
      options:
        - Content Creator
        - Builder
        - Developer
        - Tester
    validations:
      required: true

  - type: textarea
    id: experience
    attributes:
      label: Briefly describe your experience
      placeholder: "Tell us about your background, past work, skills, or examples."
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links (portfolio, GitHub, screenshots, videos)
      placeholder: "Share anything relevant that helps us understand your work."
    validations:
      required: false

  - type: textarea
    id: motivation
    attributes:
      label: Why do you want to join A Game of Cubes?
      placeholder: "1–3 sentences are enough."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---  
        ✔ After submitting, we’ll review your application as time allows.  
        ✔ All discussions stay on GitHub — no Discord required.  
        ✔ This is a community-driven, voluntary project.  

        Thank you for your interest!
